# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
