# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.CharField(max_length=120),
        ),
    ]
