# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160229_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.CharField(default='Author', max_length=120),
        ),
    ]
