# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:26
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160229_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
