# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160229_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
