# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 19:06
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160229_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('publish',)),
        ),
    ]
